### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by tobiashofmann** [tobiasqueck/ui5con2022#1]
The included backend in folder server fails to install via npm i. The included package-lock.json includes links to an SAP internal npm repository: https://int.repositories.cloud.sap

**Reproduce**

1. Be not on the SAP network!

2. 
clone repo
cd server
npm i 

Error: 

npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://int.repositories.cloud.sap/artifactory/api/npm/build-milestones-npm/xmlchars/-/xmlchars-2.2.0.tgz failed, reason: getaddrinfo ENOTFOUND int.repositories.cloud.sap
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network

**Expected results**

npm i runs without errors

**Possible solution**

Delete package-lock.json or provide a version that works from external.

**Comment by kranthie-sap** [comment]
Hi @tobiashofmann, thanks for bringing this up. To avoid differences when run outside SAP's network, I've deleted the `package-lock.json` file and added the file name to the `.gitignore` file.

**Comment by tobiashofmann** [comment]
Hi,

this might cause a philosophical question: add it or not? npm help package-lock.json says yes. Not adding it might cause problems in the future, but in theory semantic versioning of the dependencies should assure that it works just fine.

Anyway, as long as npm i on the end user side works just fine ...

**Comment by tobiasqueck** [comment]
@tobiashofmann removing it was a quick fix that @kranthie-sap and I discussed to unblock you. In general, I also prefer having the `package-lock.json` file to have a consistent setup, so I added it again, this time without internal links.
