### ISSUE TITLE
Fiori tools version

### ISSUE THREAD

**Issue by tobiashofmann** [tobiasqueck/ui5con2022#4]
The readme states to use the page map (step 5). In my case, page map gave me an error until I added the page manually via easy-ui5. Before that the page map gave an error about a missing file src/app.json

In step 4 guided development should be used to add the chart in the custom page section. At least my tooling does not list this options: custom page section nor chart. My installed version of GD is 1.6.6. 

Do some steps of the example need an updated version of the fiori tools for VS Code? If so, which version is required?

**Comment by tobiasqueck** [comment]
Please check https://github.com/tobiasqueck/ui5con2022/blob/main/README.md#before-the-demo

> For this demo, we are using features of the SAP Fiori tools that are not yet fully released. To use the features, you need to use an unlisted feature flag. If you are interested in trying this demo script, please reach out to Ashley or Tobias and we will share the feature flag.

Should I consider this as reaching out to Ashley or Tobias? :)

**Comment by tobiashofmann** [comment]
I think that for these steps the readme should contain a hint that here the feature flag is needed, or the min version where this will work.

**Comment by tobiasqueck** [comment]
Hmm. I can make the existing **hint** bold in the beginning, however, I don't really want to add it within the demo script..
