### ISSUE TITLE
Want to try the Feature flag

### ISSUE THREAD

**Issue by sammok83** [tobiasqueck/ui5con2022#5]
Hi @tobiasqueck ,

Not sure how to reach you except here, but can I get access to this feature flag please?

**For this demo, we are using features of the SAP Fiori tools that are not yet fully released. To use the features, you need to use an unlisted feature flag. If you are interested in trying this demo script, please reach out to Ashley or Tobias and we will share the feature flag.**

Thanks!

**Comment by tobiasqueck** [comment]
Sure thing, just use `"sap.ux.applicationModeler.testBetaFeatures.enableFPMFeatures": "438b6071-479e-49b4-81bf-c8a016b71c75"` in your VScode settings

**Comment by sammok83** [comment]
Thanks @tobiasqueck. That works now. 

However what isn't working is the app itself once the chart is added. Upon selecting a dropdown value / any of the filter values, the whole app is put in busy mode:
![Error](https://user-images.githubusercontent.com/10509241/188790918-d50e3c06-ca55-41b9-a1f8-8db5da2c5b75.jpg)

I can still use the tab button to navigate around the app even though it's in busy mode and execute (which works)

To replicate:
Just pull the source code, and follow the steps as per the Readme.md.
And add a line to the VSCode settings.json file as above.

If it helps, am using:
Fiori Tools - v1.7.3

Edit: Actually to get it working, I just did the following:
![2](https://user-images.githubusercontent.com/10509241/188794335-94d07870-511a-4475-9ccc-7d082bb1b394.jpg)

**Comment by tobiasqueck** [comment]
That is odd but I am able to reproduce it. I have reported it to the FPM team because I consider it a bug. I am puzzled though that I didn't run into at UI5Con.
I will also update the script to result in a working solution

**Comment by tobiasqueck** [comment]
Demo script updated with https://github.com/tobiasqueck/ui5con2022/commit/8b105f1ef3c0888fcd6f1d704cc91fd5a4da5fcf
